Add shell job block
PrefectHQ/prefect-shell pull request #55
Opened 2022-12-15 06:02 UTC by ahuang11

Closes #

### Example

### Checklist

- [ ] This pull request references any related issue by including "Closes #<ISSUE_NUMBER>"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-shell/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
 - [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-shell/blob/main/CHANGELOG.md)

2023-01-27 02:07 UTC, ahuang11 commented
Found a way to use Prefect's built-in implementation which supports Windows.

2023-01-27 02:40 UTC, desertaxle reviewed
This is looking good so far! Left a couple of comments on things that stood out to me on first review.

2023-01-27 02:40 UTC, desertaxle commented on prefect_shell/commands.py
> +class ShellJob(JobBlock):
I think we need a different name for this. Maybe something like `ShellOperation`?

Also, I think this block could feasibly have a method that handles all three steps in one call, but there's probably multiple ways we could expose that functionality.

2023-01-28 01:59 UTC, ahuang11 commented
![image](https://user-images.githubusercontent.com/15331990/215236255-c6842eeb-49b2-4e98-a30a-c7c424980ab2.png)

![image](https://user-images.githubusercontent.com/15331990/215236272-1c72ba40-57e3-4ce8-8b73-0e3e37334e3f.png)

2023-01-30 20:54 UTC, desertaxle requested changes

2023-01-30 20:54 UTC, desertaxle commented on prefect_shell/commands.py
> +                shell_process = await shell_operation.trigger()
For consistency
```suggestion
                shell_process = shell_operation.trigger()
```

2023-01-30 20:54 UTC, desertaxle commented on prefect_shell/commands.py
> +    async def run(self, **open_kwargs: Dict[str, Any]) -> List[str]:
For this method, can we do the context management ourselves? It seems like a bit much to have a context manager for a short-running command or script.

2023-01-30 20:54 UTC, desertaxle commented on prefect_shell/commands.py
> +    _documentation_url = "https://images.ctfassets.net/gm98wzqotmnx/3Nn6D7zVqrdIsGjufgpES4/abd12fa6427121f7363758aafc468d9a/Terminalicon2.png?h=250"  # noqa: E501
This URL points to an image. Should this be for `_logo_url`?

2023-02-01 17:20 UTC, desertaxle approved these changes

2023-02-01 17:31 UTC, merged