Changes to block names examples
PrefectHQ/prefect-shell pull request #64
Opened 2023-02-02 23:45 UTC by sckott

AFAICT block names have to be all lowercase, and underscores should be dashes

I ran into this when running the examples, e.g., 

Doesn't relate to any issues that I know of

### Example
```python
from prefect_shell import ShellOperation
ping_op = ShellOperation(commands=["ping -t 1 prefect.io"])
ping_op.save("BLOCK_NAME")
```

```python
ValidationError: 2 validation errors for BlockDocumentCreate
name
  name must only contain lowercase letters, numbers, and dashes (type=value_error)
__root__
  Names must be provided for block documents. (type=value_error)
```

Running versions:
- prefect: 2.7.10
- prefect-shell: 0.1.4

### Screenshots

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-shell/issues/new/choose) first.
- [x] Includes tests or only affects documentation.
- [ ] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [ ] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-shell/blob/main/CHANGELOG.md) 
    - I wasn't sure you'd want these small changes in the changelog, if accepted, but happy to do so

2023-02-02 23:47 UTC, sckott commented
e.g. of one of the pages changed:

![Screen Shot 2023-02-02 at 3 46 57 PM](https://user-images.githubusercontent.com/577668/216476565-73c74bd6-4ddd-4c33-9c35-14853e4c988f.png)

2023-02-02 23:57 UTC, ahuang11 requested changes
Thanks! I can see how that's confusing; I initially left it with underscore so users are required to change it, but having directly, runnable examples improves user experiences.

The only thing is I would keep are the example and gen_examples_catalog since those are used for UI to find and replace.

2023-02-02 23:57 UTC, ahuang11 commented on prefect_shell/commands.py
> +        shell_operation = ShellOperation.load("block-name")
The UI does a replace on "BLOCK_NAME" here.
```suggestion
        shell_operation = ShellOperation.load("BLOCK_NAME")
```

2023-02-02 23:57 UTC, ahuang11 commented on docs/gen_examples_catalog.py
> +    return re.search(r'\.load\("block-name"\)\s*$', code_example.rstrip("`"))
Needed for UI
```suggestion
    return re.search(r'\.load\("BLOCK_NAME"\)\s*$', code_example.rstrip("`"))
```

2023-02-02 23:59 UTC, sckott commented
makes sense, thanks

2023-02-03 00:01 UTC, ahuang11 approved these changes

2023-02-03 00:01 UTC, ahuang11 commented
Thank you; I'll merge after tests pass.

2023-02-03 00:17 UTC, merged